### ISSUE TITLE
Pre-Launch Package Requirements for Shiny

### ISSUE THREAD

**Issue by ichauchcc** [meganramaker/CVD-PP#1]
Hi all,

This isn’t an issue, just a friendly reminder: before launching the Shiny app, I needed to install a few additional packages to ensure it runs smoothly. For me, these were htmltools, DT, and data.table. It might be worth considering a push installation within the code to help with dependencies.

Overall, fantastic tool! Really interesting approach to building in silico tools!

Kind regards,
YuChen

**Comment by meganramaker** [comment]
Hi YuChen,

Thank you for letting me know. I will work on this asap. I’m glad you like the tool!

Sincerely,
Megan

From: Yuchen Chang ***@***.***>
Date: Wednesday, November 13, 2024 at 10:21 PM
To: meganramaker/CVD-PP ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [meganramaker/CVD-PP] Library before lunch (Issue #1)

Hi all,

This isn’t an issue, just a friendly reminder: before launching the Shiny app, I needed to install a few additional packages to ensure it runs smoothly. For me, these were htmltools, DT, and data.table. It might be worth considering a push installation within the code to help with dependencies.

Overall, fantastic tool! Really interesting approach to building in silico tools!

Kind regards,
YuChen
